# Generated by Django 4.2.6 on 2023-12-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpfulness_classification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
