# Generated by Django 4.2.6 on 2023-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_helpfulness_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpfulness_classification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
